[package]
name = "runtime-params-estimator"
version = "1.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
indicatif = "0.14"
tempfile = "3"
rand = "0.7.2"
rand_xorshift = "0.2"
gnuplot = "0.0.32"
serde_json = "1"
csv = "1.1.1"
clap = "2.33"

borsh = "0.7.0"
num-rational = "0.2.4"

near-runtime-fees = { path = "../../runtime/near-runtime-fees" }
near-crypto = { path = "../../core/crypto" }
near-vm-logic = {path = "../../runtime/near-vm-logic"}
near-vm-runner = {path = "../../runtime/near-vm-runner"}
node-runtime = { path = "../../runtime/runtime"}
near-store = { path = "../../core/store"}
near-primitives = { path = "../../core/primitives" }
neard = { path = "../../neard" }
rocksdb = { git = "https://github.com/nearprotocol/rust-rocksdb", branch="disable-thread" }

[features]
default = ["near-vm-logic/costs_counting", "near-store/single_thread_rocksdb", "near-store/no_cache", "near-vm-runner/costs_counting", "near-vm-runner/no_cache", "node-runtime/costs_counting", "node-runtime/no_cache"]