[package]
name = "near-chunks-primitives"
version = "0.1.1"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"

[dependencies]
near-chain-primitives = { path = "../chain-primitives", version = "0.1.1" }
