env:
  RUST_BACKTRACE: short

steps:
  - label: "estimate"
    command: |
      source ~/.cargo/env && set -eux
      curl --silent "https://api.buildkite.com/v2/organizations/nearprotocol/pipelines/runtime-params-estimator/builds?per_page=1" -H "Authorization: Bearer $$ESTIMATOR_BUILDKITE_TOKEN" > last_build.json
      if jq '.[]' >/dev/null 2>&1 <last_build.json; then PREV_BUILD=$( jq -r '.[] | .id' <last_build.json); buildkite-agent artifact download estimations.sqlite ./ --build ${PREV_BUILD}; fi
      cargo run --release -p estimator-warehouse -- --db estimations.sqlite estimate
      ./target/release/estimator-warehouse --db estimations.sqlite check --metric icount
    artifact_paths:
      - "estimations.sqlite"