[package]
name = "testlib"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
actix = "=0.11.0-beta.2"
actix-rt = "2"
log = "0.4"
rand = "0.7"
serde_json = "1"
futures = "0.3"
once_cell = "1.5.2"
byteorder = "1.2"
num-rational = "0.3"
hex = "0.4"

borsh = "0.9"

near-chain-configs = { path = "../../core/chain-configs" }
near-crypto = { path = "../../core/crypto" }
near-primitives = { path = "../../core/primitives" }
near-store = { path = "../../core/store" }
near-vm-errors = { path = "../../runtime/near-vm-errors" }
near-chain = { path = "../../chain/chain" }
near-test-contracts = { path = "../../runtime/near-test-contracts" }

[features]
default = []
protocol_feature_alt_bn128 = [
    "near-primitives/protocol_feature_alt_bn128",
    "near-vm-errors/protocol_feature_alt_bn128",
]
nightly_protocol_features = ["nightly_protocol",  "protocol_feature_alt_bn128"]
nightly_protocol = []
