[package]
name = "storage-usage-delta-calculator"
version = "0.1.0"
authors = ["Egor Kulikov <egor@egork.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-chain-configs = { path = "../../core/chain-configs" }
near-primitives = { path = "../../core/primitives" }
node-runtime = { path = "../../runtime/runtime" }
