[package]
name = "near-metrics"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
repository = "https://github.com/near/nearcore"
homepage = "https://github.com/near/nearcore"
description = "A fork of the lighthouse_metrics crate used to implement prometheus"

[dependencies]
prometheus = "0.11"
log = "0.4"
