[package]
name = "near-wasi"
version = "0.0.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
categories = ["wasm"]
repository = "https://github.com/nearprotocol/nearcore"
homepage = "https://github.com/nearprotocol/nearcore"
description = """
This crate implements WASI with stubs and near-vm-logics to run contracts compiled with wasm-wasi target.
"""

[dependencies]
near-vm-logic = { path = "../near-vm-logic", default-features = false, features = [] }
near-vm-errors = { path = "../near-vm-errors" }
wasmer = { package = "wasmer-near", version = "=2.0.3", optional = true, default-features = false, features = ["singlepass", "universal"] }

[features]
default = ["wasmer2_vm"]
wasmer2_vm = [ "wasmer" ]
