[package]
name = "restored-receipts-verifier"
version = "0.1.0"
authors = ["Aleksandr Logunov <alex.logunov@near.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
serde_json = "1"

near-primitives = { path = "../../core/primitives" }
neard = { path = "../../neard" }
near-store = { path = "../../core/store" }
near-chain = { path = "../../chain/chain" }
