[package]
name = "near-stress-test"
version = "0.0.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
publish = false
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.56.0"
edition = "2021"
default-run = "near-stress-test"

[[bin]]
path = "src/main.rs"
name = "near-stress-test"

[dependencies]
clap = "=3.0.0-beta.2"
actix = "=0.11.0-beta.2"
tracing = "0.1.13"
git-version = "0.3.1"
tracing-subscriber = "0.2.4"
openssl-probe = "0.1.2"
near-rust-allocator-proxy = { version = "0.4", optional = true }
once_cell = "1.5.2"
tokio = "1.1"
futures = "0.3"
tikv-jemallocator = { version = "0.4.0", optional = true }
shell-escape = "0.1.5"
anyhow = "1.0.53"
actix-rt = "2"
strum = { version = "0.20", features = ["derive"] }
rand = "0.7"

nearcore = { path = "../../nearcore" }
near-chain-configs = { path = "../../core/chain-configs" }
near-primitives = { path = "../../core/primitives" }
near-performance-metrics = { path = "../../utils/near-performance-metrics" }
near-state-viewer = { path = "../../tools/state-viewer", package = "state-viewer" }
near-network = { path = "../../chain/network" }
near-network-primitives = { path = "../../chain/network-primitives" }
near-chain = { path = "../../chain/chain" }
